using Task3;

Student student1 = new Student();
student1.Name = "Umed";
student1.GradeLevel = 1;
student1.Scores.Add(60);
student1.Scores.Add(80);
student1.Scores.Add(80);
student1.Scores.Add(80);
Student student2 = new Student();
student2.Name = "Muhammad";
student2.GradeLevel = 2;
student2.Scores.Add(90);
student2.Scores.Add(90);
student2.Scores.Add(90);
student2.Scores.Add(90);
Student student3 = new Student();
student3.Name = "Ramazon";
student3.GradeLevel = 3;
student3.Scores.Add(70);
student3.Scores.Add(60);
student3.Scores.Add(40);
student3.Scores.Add(60);
Student student4 = new Student();
student4.Name = "Voris";
student4.GradeLevel = 4;
student4.Scores.Add(90);
student4.Scores.Add(60);
student4.Scores.Add(80);
student4.Scores.Add(70);
Student student5 = new Student();
student5.Name = "Muhriddin";
student5.GradeLevel = 5;
student5.Scores.Add(80);
student5.Scores.Add(80);
student5.Scores.Add(80);
student5.Scores.Add(80);

System.Console.WriteLine(student5.GetAverage());